<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Quotation #{{ substr($quotation->uid, 0, 8) }}</title>
    <style>
        body { font-family: sans-serif; font-size: 12px; color: #333; }
        .header { width: 100%; border-bottom: 2px solid #444; padding-bottom: 10px; margin-bottom: 20px; }
        .logo { font-size: 24px; font-weight: bold; color: #d32f2f; }
        .company-info { float: right; text-align: right; }
        .title { font-size: 20px; font-weight: bold; margin-bottom: 5px; }
        .details-table { width: 100%; margin-bottom: 20px; }
        .details-table td { padding: 5px; vertical-align: top; }
        
        .items-table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        .items-table th { background-color: #f2f2f2; border: 1px solid #ddd; padding: 8px; text-align: left; }
        .items-table td { border: 1px solid #ddd; padding: 8px; }
        .text-right { text-align: right; }
        .text-center { text-align: center; }
        .fw-bold { font-weight: bold; }
        
        .totals-table { width: 40%; float: right; border-collapse: collapse; }
        .totals-table td { padding: 5px; }
        .total-row { border-top: 2px solid #333; font-size: 14px; }
        
        .footer { position: fixed; bottom: 0; width: 100%; text-align: center; font-size: 10px; color: #777; border-top: 1px solid #ddd; padding-top: 10px; }
        .terms { margin-top: 30px; border: 1px solid #eee; padding: 10px; background: #fffdfd; }
    </style>
</head>
<body>
    <div class="header">
        <div class="logo">{{ $company['name'] }}</div>
        <div class="company-info">
            {{ $company['address'] }}<br>
            Phone: {{ $company['phone'] }}
        </div>
        <div style="clear: both;"></div>
    </div>

    <div class="title">QUOTATION</div>
    
    <table class="details-table">
        <tr>
            <td width="60%">
                <strong>To:</strong><br>
                Project: {{ $quotation->project->project_name }}<br>
                Project No: {{ $quotation->project->project_number }}
            </td>
            <td width="40%">
                <strong>Date:</strong> {{ $quotation->created_at->format('d F Y') }}<br>
                <strong>Quote No:</strong> #{{ substr($quotation->uid, 0, 8) }}<br>
                <strong>Valid Until:</strong> {{ $quotation->valid_until ? $quotation->valid_until->format('d F Y') : '-' }}
            </td>
        </tr>
    </table>

    <table class="items-table">
        <thead>
            <tr>
                <th>Description / Unit</th>
                <th class="text-center">Qty</th>
                <th class="text-center">Duration</th>
                <th class="text-right">Rate (Rp)</th>
                <th class="text-right">Total (Rp)</th>
            </tr>
        </thead>
        <tbody>
            @foreach($quotation->items as $item)
            <tr>
                <td>{{ $item->unit_name }}</td>
                <td class="text-center">{{ $item->quantity }}</td>
                <td class="text-center">{{ $item->duration }} {{ $item->duration_unit }}</td>
                <td class="text-right">{{ number_format($item->rate, 0, ',', '.') }}</td>
                <td class="text-right">{{ number_format($item->total_price, 0, ',', '.') }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <table class="totals-table">
        <tr class="total-row">
            <td class="fw-bold">Total Project Value:</td>
            <td class="text-right fw-bold">Rp {{ number_format($quotation->total_project_value, 0, ',', '.') }}</td>
        </tr>
        <!-- COGS and Margin are internal, usually only Selling Price or Total Value is shown to client.
             Based on logic: Selling Price = Total Project Value (as per current implementation).
        -->
    </table>
    <div style="clear: both;"></div>

    @if($quotation->terms_conditions)
    <div class="terms">
        <strong>Terms & Conditions:</strong><br>
        {!! nl2br(e($quotation->terms_conditions)) !!}
    </div>
    @endif

    <div class="footer">
        Generated by System on {{ date('Y-m-d H:i:s') }}
        <br>
        This document is computer generated and valid without signature.
    </div>
</body>
</html>
